<?php
echo "<html xmlns=\"http://www.w3.org/1999/xhtml\" style=\"-webkit-box-sizing: border-box;box-sizing: border-box;font-family: sans-serif;line-height: 1.15;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;-ms-overflow-style: scrollbar;-webkit-tap-highlight-color: transparent;\">\n";
echo "  <head style=\"-webkit-box-sizing: inherit;box-sizing: inherit;\">\n";
echo "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;\">\n";
echo "    <title style=\"-webkit-box-sizing: inherit;box-sizing: inherit;\">Solicitud de Vacante</title>\n";
echo "  </head>\n";
echo "  <body style=\"-webkit-box-sizing: inherit;box-sizing: inherit;margin: 0;font-family: -apple-system,system-ui,BlinkMacSystemFont,&quot;Segoe UI&quot;,Roboto,&quot;Helvetica Neue&quot;,Arial,sans-serif;font-size: 1rem;font-weight: 400;line-height: 1.5;color: #292b2c;background-color: #fff;\">\n";
echo "    <div class=\"container\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;position: relative;margin-left: auto;margin-right: auto;padding-right: 15px;padding-left: 15px; min-width: 900px; max-width:1200px\">\n";
echo "      <div class=\"card text-center\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;position: relative;display: flex;-webkit-box-orient: vertical;-webkit-box-direction: normal;-webkit-flex-direction: column;-ms-flex-direction: column;flex-direction: column;background-color: #fff;border: 1px solid rgba(0,0,0,.125);border-radius: .25rem;text-align: center!important;\">\n";
echo "        <div class=\"card-header\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;padding: .75rem 1.25rem;margin-bottom: 0;background-color: #f7f7f9;border-bottom: 1px solid rgba(0,0,0,.125);border-radius: calc(.25rem - 1px) calc(.25rem - 1px) 0 0;\">\n";
echo "          ComeyCome\n";
echo "        </div>\n";
echo "        <div class=\"card-block\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;-webkit-box-flex: 1;-webkit-flex: 1 1 auto;-ms-flex: 1 1 auto;flex: 1 1 auto;padding: 1.25rem;\">\n";
echo "          <h4 class=\"card-title\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;margin-top: 0;margin-bottom: .75rem;font-family: inherit;font-weight: 500;line-height: 1.1;color: inherit;font-size: 1.5rem;\">Solicitud de Vacante\n";
echo "            <custom title=\"cantidad\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;\">(CANTIDAD)</custom>\n";
echo "          </h4>\n";
echo "          <p class=\"card-text\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;orphans: 3;widows: 3;margin-top: 0;margin-bottom: 1rem;\">Hola\n";
echo "            <custom title=\"usuario\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;\">Albert Sánchez</custom>\n";
echo "          !,<strong class=\"font-weight-bold\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;font-weight: 700;\">\n";
echo "            <custom title=\"creador\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;\">Usuario</custom>\n";
echo "          </strong> ha registrado una <strong class=\"font-weight-bold\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;font-weight: 700;\">solicitud de vacante</strong> en el ComeyCome. A continuación los detalles</p>\n";
echo "          <hr class=\"my-4\" style=\"-webkit-box-sizing: content-box;box-sizing: content-box;height: 0;overflow: visible;margin-top: 1.5rem!important;margin-bottom: 1.5rem!important;border: 0;border-top: 1px solid rgba(0,0,0,.1);\">\n";
echo "          <div class=\"d-flex justify-content-around align-items-center\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;display: flex!important;-webkit-justify-content: space-around!important;-ms-flex-pack: distribute!important;justify-content: space-around!important;-webkit-box-align: center!important;-webkit-align-items: center!important;-ms-flex-align: center!important;align-items: center!important;\">\n";
echo "\n";
echo "            <!-- OLD Puesto -->\n";
echo "            <div class=\"p-2 card\" style=\"width: 80%;-webkit-box-sizing: inherit;box-sizing: inherit;position: relative;display: flex;-webkit-box-orient: vertical;-webkit-box-direction: normal;-webkit-flex-direction: column;-ms-flex-direction: column;flex-direction: column;background-color: #fff;border: 1px solid rgba(0,0,0,.125);border-radius: .25rem;padding: .5rem .5rem!important;\">\n";
echo "              <div class=\"card-block\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;-webkit-box-flex: 1;-webkit-flex: 1 1 auto;-ms-flex: 1 1 auto;flex: 1 1 auto;padding: 1.25rem;\">\n";
echo "                <h4 class=\"card-title\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;margin-top: 0;margin-bottom: .75rem;font-family: inherit;font-weight: 500;line-height: 1.1;color: inherit;font-size: 1.5rem;\">Asesor</h4>\n";
echo "                <blockquote class=\"blockquote blockquote-reverse\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;border: 0px solid #999;page-break-inside: avoid;margin: 0 0 1rem;padding: .5rem 1rem;margin-bottom: 1rem;font-size: 1.25rem;border-left: 0;padding-right: 1rem;padding-left: 0;text-align: right;border-right: .25rem solid #eceeef;\">\n";
echo "                  <custom title=\"comentarios\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;\"></custom><p class=\"mb-0\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;orphans: 3;widows: 3;margin-top: 0;margin-bottom: 0!important;\"><em style=\"-webkit-box-sizing: inherit;box-sizing: inherit;\">Comentarios de motivos de baja</em></p>\n";
echo "                  <custom title=\"creador\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;\"><footer class=\"blockquote-footer\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;display: block;font-size: 80%;color: #636c72;\">Solicitante</footer></custom>\n";
echo "                </blockquote>\n";
echo "              </div>\n";
echo "              <ul class=\"list-group list-group-flush\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;margin-top: 0;margin-bottom: 0;display: flex;-webkit-box-orient: vertical;-webkit-box-direction: normal;-webkit-flex-direction: column;-ms-flex-direction: column;flex-direction: column;padding-left: 0;\">\n";
echo "                <li class=\"list-group-item\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;position: relative;display: flex;-webkit-flex-flow: row wrap;-ms-flex-flow: row wrap;flex-flow: row wrap;-webkit-box-align: center;-webkit-align-items: center;-ms-flex-align: center;align-items: center;padding: .75rem 1.25rem;margin-bottom: -1px;background-color: #fff;border: 1px solid rgba(0,0,0,.125);border-top-right-radius: .25rem;border-top-left-radius: .25rem;border-right: 0;border-left: 0;border-radius: 0;\">\n";
echo "\n";
echo "                    <div class=\"col-6 text-right\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;position: relative;width: 100%;min-height: 1px;padding-right: 15px;padding-left: 15px;-webkit-box-flex: 0;-webkit-flex: 0 0 50%;-ms-flex: 0 0 50%;flex: 0 0 50%;max-width: 50%;text-align: right!important;\">\n";
echo "                      UDN / Area / Departamento:\n";
echo "                    </div>\n";
echo "                    <div class=\"col-6 text-left\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;position: relative;width: 100%;min-height: 1px;padding-right: 15px;padding-left: 15px;-webkit-box-flex: 0;-webkit-flex: 0 0 50%;-ms-flex: 0 0 50%;flex: 0 0 50%;max-width: 50%;text-align: left!important;\">\n";
echo "                      <custom style=\"-webkit-box-sizing: inherit;box-sizing: inherit;\">UDN - Area - Departamento</custom>\n";
echo "                    </div>\n";
echo "\n";
echo "                </li>\n";
echo "                <li class=\"list-group-item\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;position: relative;display: flex;-webkit-flex-flow: row wrap;-ms-flex-flow: row wrap;flex-flow: row wrap;-webkit-box-align: center;-webkit-align-items: center;-ms-flex-align: center;align-items: center;padding: .75rem 1.25rem;margin-bottom: -1px;background-color: #fff;border: 1px solid rgba(0,0,0,.125);border-right: 0;border-left: 0;border-radius: 0;\">\n";
echo "\n";
echo "                    <div class=\"col-6 text-right\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;position: relative;width: 100%;min-height: 1px;padding-right: 15px;padding-left: 15px;-webkit-box-flex: 0;-webkit-flex: 0 0 50%;-ms-flex: 0 0 50%;flex: 0 0 50%;max-width: 50%;text-align: right!important;\">\n";
echo "                      Puesto:\n";
echo "                    </div>\n";
echo "                    <div class=\"col-6 text-left\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;position: relative;width: 100%;min-height: 1px;padding-right: 15px;padding-left: 15px;-webkit-box-flex: 0;-webkit-flex: 0 0 50%;-ms-flex: 0 0 50%;flex: 0 0 50%;max-width: 50%;text-align: left!important;\">\n";
echo "                      <custom style=\"-webkit-box-sizing: inherit;box-sizing: inherit;\">Puesto (Puesto RRHH) -> Código</custom>\n";
echo "                    </div>\n";
echo "\n";
echo "                </li>\n";
echo "                <li class=\"list-group-item\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;position: relative;display: flex;-webkit-flex-flow: row wrap;-ms-flex-flow: row wrap;flex-flow: row wrap;-webkit-box-align: center;-webkit-align-items: center;-ms-flex-align: center;align-items: center;padding: .75rem 1.25rem;margin-bottom: -1px;background-color: #fff;border: 1px solid rgba(0,0,0,.125);border-right: 0;border-left: 0;border-radius: 0;\">\n";
echo "\n";
echo "                    <div class=\"col-6 text-right\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;position: relative;width: 100%;min-height: 1px;padding-right: 15px;padding-left: 15px;-webkit-box-flex: 0;-webkit-flex: 0 0 50%;-ms-flex: 0 0 50%;flex: 0 0 50%;max-width: 50%;text-align: right!important;\">\n";
echo "                      PDV/Oficina:\n";
echo "                    </div>\n";
echo "                    <div class=\"col-6 text-left\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;position: relative;width: 100%;min-height: 1px;padding-right: 15px;padding-left: 15px;-webkit-box-flex: 0;-webkit-flex: 0 0 50%;-ms-flex: 0 0 50%;flex: 0 0 50%;max-width: 50%;text-align: left!important;\">\n";
echo "                      <custom style=\"-webkit-box-sizing: inherit;box-sizing: inherit;\">PDV</custom>\n";
echo "                    </div>\n";
echo "\n";
echo "                </li>\n";
echo "                <li class=\"list-group-item\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;position: relative;display: flex;-webkit-flex-flow: row wrap;-ms-flex-flow: row wrap;flex-flow: row wrap;-webkit-box-align: center;-webkit-align-items: center;-ms-flex-align: center;align-items: center;padding: .75rem 1.25rem;margin-bottom: -1px;background-color: #fff;border: 1px solid rgba(0,0,0,.125);border-right: 0;border-left: 0;border-radius: 0;\">\n";
echo "\n";
echo "                    <div class=\"col-6 text-right\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;position: relative;width: 100%;min-height: 1px;padding-right: 15px;padding-left: 15px;-webkit-box-flex: 0;-webkit-flex: 0 0 50%;-ms-flex: 0 0 50%;flex: 0 0 50%;max-width: 50%;text-align: right!important;\">\n";
echo "                      Fecha de Inicio:\n";
echo "                    </div>\n";
echo "                    <div class=\"col-6 text-left\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;position: relative;width: 100%;min-height: 1px;padding-right: 15px;padding-left: 15px;-webkit-box-flex: 0;-webkit-flex: 0 0 50%;-ms-flex: 0 0 50%;flex: 0 0 50%;max-width: 50%;text-align: left!important;\">\n";
echo "                      <custom style=\"-webkit-box-sizing: inherit;box-sizing: inherit;\">2017-08-07</custom>\n";
echo "                    </div>\n";
echo "\n";
echo "                </li>\n";
echo "                <div class=\"card-block text-center\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;-webkit-box-flex: 1;-webkit-flex: 1 1 auto;-ms-flex: 1 1 auto;flex: 1 1 auto;padding: 1.25rem;text-align: center!important;\">\n";
echo "                <p class=\"text-center\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;orphans: 3;widows: 3;margin-top: 0;margin-bottom: 1rem;text-align: center!important;\">\n";
echo "                  <span class=\"btn btn-danger btn-lg\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;display: inline-block;font-weight: 400;line-height: 1.25;text-align: center;white-space: nowrap;vertical-align: middle;-webkit-user-select: none;-moz-user-select: none;-ms-user-select: none;user-select: none;border: 1px solid transparent;padding: .75rem 1.5rem;font-size: 1.25rem;border-radius: .3rem;-webkit-transition: all .2s ease-in-out;-o-transition: all .2s ease-in-out;transition: all .2s ease-in-out;color: #fff;background-color: #d9534f;border-color: #d9534f;\">Denegada</span>\n";
echo "                  <span class=\"btn btn-success btn-lg\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;display: inline-block;font-weight: 400;line-height: 1.25;text-align: center;white-space: nowrap;vertical-align: middle;-webkit-user-select: none;-moz-user-select: none;-ms-user-select: none;user-select: none;border: 1px solid transparent;padding: .75rem 1.5rem;font-size: 1.25rem;border-radius: .3rem;-webkit-transition: all .2s ease-in-out;-o-transition: all .2s ease-in-out;transition: all .2s ease-in-out;color: #fff;background-color: #5cb85c;border-color: #5cb85c;\">Aprobada</span>\n";
echo "                  <a href=\"https://operaciones.pricetravel.com.mx/config/aprobaciones_pendientes.php\" class=\"btn btn-primary btn-lg\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;background-color: #0275d8;-webkit-text-decoration-skip: objects;color: #fff;text-decoration: underline;-ms-touch-action: manipulation;touch-action: manipulation;display: inline-block;font-weight: 400;line-height: 1.25;text-align: center;white-space: nowrap;vertical-align: middle;-webkit-user-select: none;-moz-user-select: none;-ms-user-select: none;user-select: none;border: 1px solid transparent;padding: .75rem 1.5rem;font-size: 1.25rem;border-radius: .3rem;-webkit-transition: all .2s ease-in-out;-o-transition: all .2s ease-in-out;transition: all .2s ease-in-out;border-color: #0275d8;\">Ver Solicitud</a>\n";
echo "                </p>\n";
echo "              </div>\n";
echo "            </ul></div>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "        <div class=\"card-footer text-muted\" style=\"-webkit-box-sizing: inherit;box-sizing: inherit;padding: .75rem 1.25rem;background-color: #f7f7f9;border-top: 1px solid rgba(0,0,0,.125);border-radius: 0 0 calc(.25rem - 1px) calc(.25rem - 1px);color: #636c72!important;\">\n";
echo "          © ComeyCome 2017. Todos los derechos reservados\n";
echo "        </div>\n";
echo "      </div>\n";
echo "\n";
echo "    </div>\n";
echo "  </body>\n";
echo "</html>\n";
echo "\n";
?>
